### ISSUE TITLE
Erro exemplo Setter - Cap 05

### ISSUE THREAD

**Issue by Adler7Nine** [leonardovilarinho/vue-livro-avanco#2]
Boa tarde Leonardo, estou com um problema no exemplo do "setter" no capítulo 5, item 5.3 Computed Properties, quando vamos exemplificar, fiz o código do livro e o erro ocorre. Poderia me ajudar por favor! Obrigado!
Meu código: 
```javascript
nomeFormatado2(){
      get: function () {
        console.log('executando get');
        return this.nome.toUpperCase();
      },
      set: function (novoValor) {
        console.log('executando set');
        this.nome = novoValor.substring(0,3);
      }
    }
 }
```

Erro:
> Failed to compile.

> ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
>Module build failed: SyntaxError: C:/Adler/Cursos/Vue_Livro/manipulando-dados/src/App.vue: Unexpected token (67:20)

```
  65 |   
  66 |     nomeFormatado2(){
> 67 |       get: function () {
     |                     ^
  68 |         console.log('executando get');
  69 | 
  70 |         return this.nome.toUpperCase();

 @ ./src/App.vue 8:0-100 9:0-113
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by Adler7Nine** [comment]
Problema resolvido.
O nome do setter é seguido de ":", e eu coloquei "()", copiei de forma incorreta.

**Comment by leonardovilarinho** [comment]
@Adler7Nine desculpe a demora, no final de semana eu me afasto um pouco de tudo.

Que bom que conseguiu corrigir, qualquer coisa basta abrir uma nova insue.
