### ISSUE TITLE
Problema ao executar o npm Install

### ISSUE THREAD

**Issue by Adler7Nine** [leonardovilarinho/vue-livro-avanco#3]
Boa tarde Leonardo, tenho outro problema relacionado ao npm install, sempre criamos o projeto (vue init webpack-simple nome-do-projeto), entro na pasta do projeto, e rodo o npm install babel-preset-es2015, o mesmo sempre mostra o erro abaixo: (Obrigado!)
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! path C:\manipulando-dados\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
npm ERR! Error: EPERM: operation not permitted, lstat 'C:\manipulando-dados\node_modules\fsevents\node_modules'
npm ERR!  { [Error: EPERM: operation not permitted, lstat 'C:\manipulando-dados\node_modules\fsevents\node_modules']
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, lstat \'C:\\manipulando-dados\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path:
npm ERR!    'C:\\manipulando-dados\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Adler\AppData\Roaming\npm-cache\_logs\2019-02-23T15_30_29_748Z-debug.log

2019-02-23T15_30_29_748Z-debug.log:
Mesmo erro descrito acima.

**Comment by leonardovilarinho** [comment]
Boa tarde,

esse erro é de permissão, você está colocando o projeto no `C:` do Windows, ao usar o `C:` é necessária a permissão de administrador. Para resolver, seria mais fácil colocar o projeto no `D:` ou em alguma pasta pessoal, como a pasta de `Documentos`.
