### ISSUE TITLE
Oque acontece neste caso ?

### ISSUE THREAD

**Issue by HenriqueOmena** [leonardovilarinho/vue-livro-avanco#4]
Ola como vai primeiramente muito obrigado pelo seu compartilhamento de conhecimento, 
Meu caro fiz um teste aqui e nao consegui entender uma coisa que para você talvez seja simples

onde declaramos v-text 
`<h1 v-once v-text="titulo"></h1>`
Percebi q a outra forma seria assim 
`<h1>{{	titulo	}}</h1>`

Ate ai tudo bem mas quando mando atualizar o vue altera apenas a segunda opção pelo {{ titulo }}

sabe por que isso ocorre?  meu codigo para este teste esta assim
```vue
<template.>
    <div id="app".>
        <h1 v-once v-text="titulo".></h1.>
        <h1.>{{	titulo	}}</h1.>
        <h2.>{{	subtitulo	}}</h2.>
        <div v-if="tarefas.length <=0".>
            Sem Tarefas definidas
        </div.>
        <div v-if="tarefas.length .> 0".>
            Existem {{tarefas.length}} tarefas
            <ul.>
                <li v-for="tarefa in tarefas".>{{ tarefa }}</li.>
            </ul.>
            <button	v-on:click="tarefas	=[]".>Limpar</button.>
        </div.>
            <input	v-bind:disabled="tarefas.length	==	0"	v-model="subtitulo"	type=" text" placeholder="Descrição".>
    </div.>
</template.>

<script.>
    export default {
        name: 'lv-tarefas',
        data () {
            return {
                titulo:	'Listagem	de	tarefas',
                subtitulo:	'Defina	uma	descrição',
                tarefas:	[],
            }
        },
        mounted() {
            setTimeout(	()=.>{
                this.titulo  = "Novo itulo"
                this.tarefas = [
                    'tarefa	1',
                    'tarefa	2',
                    'tarefa	3',
                    'tarefa	4' ]
            },	3000	)
        }
    }
</script.>
```

> coloquei um ponto em casa fechamento pois estava dando erro na hora de colar o codigo aqui mas no meu original nao existe esse .> em todos os elemetos

e o resultado sai assim 

![image](https://user-images.githubusercontent.com/35804326/55289142-5cf39300-53ba-11e9-89a4-30e7244b8e5c.png)

ou seja alterou so o segundo sabe me dizer pq ? 

Obrigado !!!!

**Comment by leonardovilarinho** [comment]
Olá, tudo certo e você?

Fiz isso de forma intencional, realmente usar `v-text` e `{{ }}` é a mesma coisa. A questão aí é o uso da diretiva `v-once`, como mencionado no livro, ela informa ao Vue que o elemento HTML será interpretado apenas UMA vez.

Ou seja, ao usar: `<h1 v-once v-text="titulo"></h1>`, você diz "interprete o código no H1 apenas na primeira execução", logo quando a variável `titulo` for trocada ele não irá atualizar o H1, dado a presença da diretiva `v-once`. Você pode retirar ela, deixando `<h1 v-text="titulo"></h1>`, ao fazer isso você vai ver que tanto esse quanto o outro título irão atualizar.

Em termos mais técnicos, frameworks como o Vue fazem data binding com as variáveis escolhidas pelo dev, esse data binding nada mais é que um observador, onde o framework fica escutando o valor da variável, e quando alterado atualiza os elementos do DOM que usam essa variável. O `v-once` desliga o data binding no elemento em qual foi declarado, assim ele para de ouvir as alterações para aquele elemento (H1).

Espero que eu tenha conseguido explicar rs, qualquer dúvida basta abrir novos issues.
